# Generated by Django 3.0.7 on 2020-06-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('memo', models.CharField(max_length=255)),
                ('latitudes', models.FloatField(max_length=10)),
                ('longitudes', models.FloatField(max_length=10)),
            ],
        ),
    ]
